name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        export DOCKER_BUILDKIT=1
        docker buildx build . \
        --cache-from type=gha,scope=${{ github.ref }} \
        --cache-from type=gha,scope=${{ github.base_ref }} \
        --cache-to type=gha,mode=max,scope=${{ github.ref }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Prepare
      run: echo hello world
    - name: Deploy
      run: helm --help

