name: Rust

on:
  workflow_call:
    inputs:
      perform_deploy:
        required: true
        type: boolean
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        export DOCKER_BUILDKIT=1
        # docker build .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Prepare
      uses: trstringer/manual-approval@v1
      run: echo hello world
    - name: Deploy
      run: helm --help

